steps:
  - name:  'gcr.io/cloud-builders/mvn'
    args:  ['install']
  - name:  'gcr.io/cloud-builders/docker'
    args:  ['build','--tag=gcr.io/$PROJECT_ID/chatbot-server-api','.']
images:   ['gcr.io/$PROJECT_ID/chatbot-server-api']